# visit https://github.com/mojombo/jekyll/wiki/Configuration for more settings

paginate: 10 # pagination based on number of posts
paginate_path: "page:num"
exclude: ["README.md"] # files to exclude
highlighter: rouge
markdown: kramdown
disqus: gkvs
google_analytics: UA-101391194-1
title: gkvs

defaults:
  -
    scope:
      path: "" # empty string for all files
    values:
      title: gkvs

description: Generic Key-Value Storage
author:
  name: gkvs
  email: alex@gkvs.rocks
  github: gkvs
  twitter: realgkvs
  pinterest: gkvs
  linkedin: gkvs
  bio: gkvs
  email_md5: 75b2c5191f304734f8f09c4b10a7f40e

rss_path: feed.xml
categories_path: categories.html
tags_path: tags.html

# set it as url of an image
sidebar_background_image: https://www.dropbox.com/s/g9h23zrycedxtk5/sky.png?raw=1

BASE_PATH:

plugins:
  - jekyll-paginate
